config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'home#index'
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :sales
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :categories
  belongs_to :suppliers
  has_many :warehouse_records
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :client
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :products
  has_many :warehouse_records
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/warehouse_record.rb
class WarehouseRecord < ApplicationRecord
  belongs_to :supplier
  belongs_to :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.json { head :no_content}
        format.js
      else
        format.json { render json: @category.errors.full_messages, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.json { head :no_content}
        format.js
      else
        format.json { render json: @category.errors.full_messages, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.json { head :no_content}
      format.js
    end
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params
        .require(:category)
        .permit(:nombre, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category, remote: true) do |f| %>
  <div class="form-group">
    <h4 class="control-label">Datos de la categoria</h4>
  </div>

  <div class="item form-group<%= @category.erros[:nombre].any? ? ' has error has-feedback' : ''%>">
    <%= f.label :nombre , "Nombre de categoria: "%>
    <div class="input-group">
      <%= f.text_field :nombre , {:class=>"form-control", :placeholder=>"Introduzca nombre de la categoria ..."}%>
      <% if @category.errors[:nombre].any? %>
        <p class="bg-danger"><%= @category.errors[:nombre].to_s[/\w([^"]*)/]%></p>
      <% end %>
    </div>
  </div>

  <div class="item form-group<%= @category.erros[:description].any? ? ' has error has-feedback' : ''%>">
    <%= f.label :description , "Descripcion de categoria: "%>
    <div class="input-group">
      <%= f.text_area :description , {:class=>"form-control", :placeholder=>"Introduzca la descripcion  de la categoria ..."}%>
      <% if @category.errors[:description].any? %>
        <p class="bg-danger"><%= @category.errors[:description].to_s[/\w([^"]*)/]%></p>
      <% end %>
    </div>
  </div>

  <div class="actions col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
    <%= f.submit @category.new_record? ? "crear categoria" : "Actualizar Categoria", :class => "btn btn-success" %>
  </div>
<% end %>

app/views/categories/_modal_categorias.html.erb
<!-- Modal -->

<div class="modal fade" id="modalCategorias" tabindex="-1" role="dialog" arial-labelledby="modalCategorias">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-categorias-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body-categorias modal-body" id="modal-body-categorias">
      </div>
      <div class="modal-footer" id="modal-footer-categorias">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"> cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<h1 class="h3 mb-2 text-gray-800">Categorias de productos</h1>

<div>
  <%= link_to new_category_path, {remote: true, class: "btn btn-info", id: "agregar-categoria-btn"} do %>
    <span class="fas fa-plus-square"></span>
  <% end %>
</div>
<br/>

<div class="card shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
      <table id="tablaCategories" class="table table-border" width="100%">
        <thead>
          <tr>
            <th>Nombre categoria</th>
            <th>Descripcion</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |cat| %>  
            <tr id="categoria_<%= cat.id %>">
              <td><%= cat.nombre %></td>
              <td><%= cat.description%></td>
              <td>
                <%= link_to "Editar", edit_category_path(cat), html_options = {class: "btn btn-info btn-xs", remote: true}%>
                <%= link_to "Borrar", cat, remote: true, method: :delete, data: { confirm:"Borrar categoria: #{cat.nombre}? " }, class: "btn btn-danger btn-xs"%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= render 'modal_categorias' %>

app/views/categories/new.js.erb
//Render the new form
$('.modal-body-categorias').html('<%= j render("form") %>');

// Add the dialog title
$('#modal-categorias-title').html("Nueva categoria");

//Show the dynamic dialog
$('#modalCategorias').modal("show");

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>